<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ozelot" nsURI="http://www.thm.de/ozelot" nsPrefix="ozelot">
  <eClassifiers xsi:type="ecore:EClass" name="Mod">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authors" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//Item" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="#//Block" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iconPath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toolProperty" eType="#//ToolProperty"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iconPath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="glows" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxStackSize" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="64"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isImmuneToFire" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itemId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rarity" lowerBound="1"
        eType="#//Rarity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creativeModeTab" lowerBound="1"
        eType="#//CreativeModeTab"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="translations" upperBound="-1"
        eType="#//Translation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onAttack" upperBound="-1"
        eType="#//SelfOtherEffect" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onTick" upperBound="-1"
        eType="#//OnTickEffect" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onUse" upperBound="-1"
        eType="#//Effect" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FoodItem" eSuperTypes="#//Item">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nutrition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="4"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="saturation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="0.3"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMeat" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAlwaysEdible" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="afterEating" upperBound="-1"
        eType="#//Effect" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToolProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="onStepOn" upperBound="-1"
        eType="#//Effect" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onDestroyed" upperBound="-1"
        eType="#//Effect" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onPlaced" upperBound="-1"
        eType="#//Effect" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Effect">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="potionEffect" lowerBound="1"
        eType="#//PotionEffect"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelfOtherEffect" eSuperTypes="#//Effect">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSelf" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OnTickEffect" eSuperTypes="#//Effect">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="needsSelected" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Translation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lang" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="en_us"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PotionEffect">
    <eLiterals name="MOVEMENT_SPEED"/>
    <eLiterals name="MOVEMENT_SLOWDOWN" value="1"/>
    <eLiterals name="DIG_SPEED" value="2"/>
    <eLiterals name="DIG_SLOWDOWN" value="3"/>
    <eLiterals name="DAMAGE_BOOST" value="4"/>
    <eLiterals name="HEAL" value="5"/>
    <eLiterals name="HARM" value="6"/>
    <eLiterals name="JUMP" value="7"/>
    <eLiterals name="CONFUSION" value="8"/>
    <eLiterals name="REGENERATION" value="9"/>
    <eLiterals name="DAMAGE_RESISTANCE" value="10"/>
    <eLiterals name="FIRE_RESISTANCE" value="11"/>
    <eLiterals name="WATER_BREATHING" value="12"/>
    <eLiterals name="INVISIBILITY" value="13"/>
    <eLiterals name="BLINDNESS" value="14"/>
    <eLiterals name="NIGHT_VISION" value="15"/>
    <eLiterals name="HUNGER" value="16"/>
    <eLiterals name="WEAKNESS" value="17"/>
    <eLiterals name="POISON" value="18"/>
    <eLiterals name="WITHER" value="19"/>
    <eLiterals name="HEALTH_BOOST" value="20"/>
    <eLiterals name="ABSORPTION" value="21"/>
    <eLiterals name="SATURATION" value="22"/>
    <eLiterals name="GLOWING" value="23"/>
    <eLiterals name="LEVITATION" value="24"/>
    <eLiterals name="LUCK" value="25"/>
    <eLiterals name="UNLUCK" value="26"/>
    <eLiterals name="SLOW_FALLING" value="27"/>
    <eLiterals name="CONDUIT_POWER" value="28"/>
    <eLiterals name="DOLPHINS_GRACE" value="29"/>
    <eLiterals name="BAD_OMEN" value="30"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Rarity">
    <eLiterals name="COMMON"/>
    <eLiterals name="UNCOMMON" value="1"/>
    <eLiterals name="RARE" value="2"/>
    <eLiterals name="EPIC" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CreativeModeTab">
    <eLiterals name="BUILDING_BLOCKS"/>
    <eLiterals name="DECORATIONS" value="1"/>
    <eLiterals name="REDSTONE" value="2"/>
    <eLiterals name="TRANSPORTATION" value="3"/>
    <eLiterals name="MISC" value="4"/>
    <eLiterals name="FOOD" value="5"/>
    <eLiterals name="TOOLS" value="6"/>
    <eLiterals name="COMBAT" value="7"/>
    <eLiterals name="BREWING" value="8"/>
  </eClassifiers>
</ecore:EPackage>
