modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="examplemod"
version="0.0.1"
displayName="Example Mod"
credits="todo"
authors="todo"
# logoFile="todo"
description='''
todo
'''


[[dependencies.examplemod]]
   modId="forge"
   mandatory=true
   versionRange="[40.1.84,)"
   ordering="NONE"
   side="BOTH"

# [[dependencies.examplemod]]
#    modId="curios"
#    mandatory=true
#    versionRange="[1.18.2-5,)"
#    ordering="NONE"
#    side="BOTH"

# [[dependencies.examplemod]]
#     modId="caelus"
#     mandatory=true
#     versionRange="[1.18.1-3,)"
#     ordering="NONE"
#     side="BOTH"

[[dependencies.examplemod]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.2]"
   ordering="NONE"
   side="BOTH"
