package ozelot.generator.content;

import org.eclipse.core.resources.IProject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.Conversions;
import org.eclipse.xtext.xbase.lib.InputOutput;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import ozelot.Mod;
import ozelot.generator.FileGenerator;
import ozelot.generator.FolderGenerator;

@SuppressWarnings("all")
public class ContentGenerator {
  public static void run(final IProject project, final Mod mod) {
    InputOutput.<String>println("\n\nContentSetup:");
    String _iconPath = mod.getIconPath();
    String _plus = ("Coping \"" + _iconPath);
    String _plus_1 = (_plus + "\" to \"");
    String _baseFolder = FolderGenerator.getBaseFolder(mod);
    String _plus_2 = (_plus_1 + _baseFolder);
    String _plus_3 = (_plus_2 + "/src/main/resources\"");
    InputOutput.<String>println(_plus_3);
    String _replace = mod.getName().replace(" ", "");
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("import org.slf4j.Logger;");
    _builder.newLine();
    _builder.append("import com.mojang.logging.LogUtils;");
    _builder.newLine();
    _builder.append("import net.minecraftforge.common.MinecraftForge;");
    _builder.newLine();
    _builder.append("import net.minecraftforge.eventbus.api.IEventBus;");
    _builder.newLine();
    _builder.append("import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;");
    _builder.newLine();
    {
      int _size = mod.getItems().size();
      boolean _greaterThan = (_size > 0);
      if (_greaterThan) {
        _builder.append("import ");
        String _basePackage = FolderGenerator.getBasePackage(mod);
        String _plus_4 = (_basePackage + ".item.ItemInitGen");
        _builder.append(_plus_4);
        _builder.append(";");
        _builder.newLineIfNotEmpty();
      }
    }
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("public static final String MOD_ID = \"");
    String _modId = mod.getModId();
    _builder_1.append(_modId);
    _builder_1.append("\";");
    _builder_1.newLineIfNotEmpty();
    _builder_1.append("public static final Logger LOGGER = LogUtils.getLogger();");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("public ");
    String _replace_1 = mod.getName().replace(" ", "");
    _builder_1.append(_replace_1);
    _builder_1.append("Gen() {");
    _builder_1.newLineIfNotEmpty();
    _builder_1.append("\t");
    _builder_1.append("IEventBus eventBus = FMLJavaModLoadingContext.get().getModEventBus();");
    _builder_1.newLine();
    {
      int _size_1 = mod.getItems().size();
      boolean _greaterThan_1 = (_size_1 > 0);
      if (_greaterThan_1) {
        _builder_1.append("\t");
        _builder_1.append("ItemInitGen.register(eventBus);");
        _builder_1.newLine();
      }
    }
    _builder_1.append("\t");
    _builder_1.append("// BlockInit.register(eventBus);");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("// EffectInit.register(eventBus);");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("MinecraftForge.EVENT_BUS.register(this);");
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    FileGenerator.generateJavaClass(project, _replace, "", "", _builder.toString(), _builder_1.toString(), mod, 
      true, 
      false);
    String _baseFolder_1 = FolderGenerator.getBaseFolder(mod);
    String _plus_5 = (_baseFolder_1 + "/src/main/resources/META-INF");
    StringConcatenation _builder_2 = new StringConcatenation();
    _builder_2.append("modLoader=\"javafml\"");
    _builder_2.newLine();
    _builder_2.append("loaderVersion=\"[40,)\"");
    _builder_2.newLine();
    _builder_2.append("license=\"All Rights Reserved\"");
    _builder_2.newLine();
    _builder_2.newLine();
    _builder_2.append("[[mods]]");
    _builder_2.newLine();
    _builder_2.append("modId=\"");
    String _modId_1 = mod.getModId();
    _builder_2.append(_modId_1);
    _builder_2.append("\"");
    _builder_2.newLineIfNotEmpty();
    _builder_2.append("version=\"");
    String _version = mod.getVersion();
    _builder_2.append(_version);
    _builder_2.append("\"");
    _builder_2.newLineIfNotEmpty();
    _builder_2.append("displayName=\"");
    String _name = mod.getName();
    _builder_2.append(_name);
    _builder_2.append("\"");
    _builder_2.newLineIfNotEmpty();
    _builder_2.append("credits=\"This mod was created with the Ozelot project.\"");
    _builder_2.newLine();
    _builder_2.append("authors=\"");
    String _authors = mod.getAuthors();
    _builder_2.append(_authors);
    _builder_2.append("\"");
    _builder_2.newLineIfNotEmpty();
    _builder_2.append("logoFile=\"");
    String _last = IterableExtensions.<String>last(((Iterable<String>)Conversions.doWrapArray(mod.getIconPath().split("/"))));
    _builder_2.append(_last);
    _builder_2.append("\"");
    _builder_2.newLineIfNotEmpty();
    _builder_2.append("description=");
    _builder_2.append("\'\'\'");
    _builder_2.newLineIfNotEmpty();
    String _description = mod.getDescription();
    _builder_2.append(_description);
    _builder_2.newLineIfNotEmpty();
    _builder_2.append("\'\'\'");
    _builder_2.newLineIfNotEmpty();
    _builder_2.newLine();
    _builder_2.newLine();
    _builder_2.append("[[dependencies.");
    String _modId_2 = mod.getModId();
    _builder_2.append(_modId_2);
    _builder_2.append("]]");
    _builder_2.newLineIfNotEmpty();
    _builder_2.append("   ");
    _builder_2.append("modId=\"forge\"");
    _builder_2.newLine();
    _builder_2.append("   ");
    _builder_2.append("mandatory=true");
    _builder_2.newLine();
    _builder_2.append("   ");
    _builder_2.append("versionRange=\"[40.1.84,)\"");
    _builder_2.newLine();
    _builder_2.append("   ");
    _builder_2.append("ordering=\"NONE\"");
    _builder_2.newLine();
    _builder_2.append("   ");
    _builder_2.append("side=\"BOTH\"");
    _builder_2.newLine();
    _builder_2.newLine();
    _builder_2.append("# [[dependencies.");
    String _modId_3 = mod.getModId();
    _builder_2.append(_modId_3);
    _builder_2.append("]]");
    _builder_2.newLineIfNotEmpty();
    _builder_2.append("#    modId=\"curios\"");
    _builder_2.newLine();
    _builder_2.append("#    mandatory=true");
    _builder_2.newLine();
    _builder_2.append("#    versionRange=\"[1.18.2-5,)\"");
    _builder_2.newLine();
    _builder_2.append("#    ordering=\"NONE\"");
    _builder_2.newLine();
    _builder_2.append("#    side=\"BOTH\"");
    _builder_2.newLine();
    _builder_2.newLine();
    _builder_2.append("# [[dependencies.");
    String _modId_4 = mod.getModId();
    _builder_2.append(_modId_4);
    _builder_2.append("]]");
    _builder_2.newLineIfNotEmpty();
    _builder_2.append("#     modId=\"caelus\"");
    _builder_2.newLine();
    _builder_2.append("#     mandatory=true");
    _builder_2.newLine();
    _builder_2.append("#     versionRange=\"[1.18.1-3,)\"");
    _builder_2.newLine();
    _builder_2.append("#     ordering=\"NONE\"");
    _builder_2.newLine();
    _builder_2.append("#     side=\"BOTH\"");
    _builder_2.newLine();
    _builder_2.newLine();
    _builder_2.append("[[dependencies.");
    String _modId_5 = mod.getModId();
    _builder_2.append(_modId_5);
    _builder_2.append("]]");
    _builder_2.newLineIfNotEmpty();
    _builder_2.append("   ");
    _builder_2.append("modId=\"minecraft\"");
    _builder_2.newLine();
    _builder_2.append("   ");
    _builder_2.append("mandatory=true");
    _builder_2.newLine();
    _builder_2.append("   ");
    _builder_2.append("versionRange=\"[1.18.2]\"");
    _builder_2.newLine();
    _builder_2.append("   ");
    _builder_2.append("ordering=\"NONE\"");
    _builder_2.newLine();
    _builder_2.append("   ");
    _builder_2.append("side=\"BOTH\"");
    _builder_2.newLine();
    FileGenerator.generateFile(project, 
      "mods.toml", _plus_5, _builder_2, 
      true);
    String _baseFolder_2 = FolderGenerator.getBaseFolder(mod);
    String _plus_6 = (_baseFolder_2 + "/src/main/resources");
    StringConcatenation _builder_3 = new StringConcatenation();
    _builder_3.append("{");
    _builder_3.newLine();
    _builder_3.append("    ");
    _builder_3.append("\"pack\": {");
    _builder_3.newLine();
    _builder_3.append("        ");
    _builder_3.append("\"description\": \"");
    String _modId_6 = mod.getModId();
    _builder_3.append(_modId_6, "        ");
    _builder_3.append(" resources\",");
    _builder_3.newLineIfNotEmpty();
    _builder_3.append("        ");
    _builder_3.append("\"pack_format\": 9,");
    _builder_3.newLine();
    _builder_3.append("        ");
    _builder_3.append("\"forge:resource_pack_format\": 8,");
    _builder_3.newLine();
    _builder_3.append("        ");
    _builder_3.append("\"forge:data_pack_format\": 9");
    _builder_3.newLine();
    _builder_3.append("    ");
    _builder_3.append("}");
    _builder_3.newLine();
    _builder_3.append("}");
    _builder_3.newLine();
    FileGenerator.generateFile(project, 
      "pack.mcmeta", _plus_6, _builder_3, 
      true);
    ItemGenerator.run(project, mod);
  }
}
